In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import mysql.connector

In [3]:
#pip install mysql-connector-python

In [4]:
#Establishing a connection with the database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="******"
    
)

print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x7f842c441c90>

In [5]:
Dedupe_tables =  pd.read_sql_query('SHOW TABLES FROM Dedupe', mydb)

In [6]:
Dedupe_tables

      Tables_in_dedupe
0  combinedsamplesq1q3

In [7]:
df = pd.read_sql_query('SELECT * FROM Dedupe.combinedsamplesq1q3', mydb)

In [8]:
df

,BUSINESS_UNIT,PSC_CODE,OBJ_CODE,SUB_OBJ_DESCR,ORDER_DATE,ORDER_TITLE,LINE_DESCRIPTION,VENDOR_NAME,VENDOR_COUNTRY,COST,clean_title,clean_desc,clean_title_desc
0,ADDIS,V212,TRANSPORT OF THINGS,HHE PACKAGE&CRATING,Thu Apr 23 2020 00:56:56 GMT-0400 (EDT),state/gso/shiping-aaron NAME hhe exp airfreigh...,air freight service for the export of mr. NAME...,ETHIOPIAN AIRLINES,ETH,7963.4868,state shiping aaron name airfreight service,freight service export name cardona shipmen...,state shiping aaron name airfreight service...
1,NEWDE,S206,GRANTS/CONT/SUBSIDY,VALUE-ADDED TAXES,Thu Apr 16 2020 10:17:00 GMT-0400 (EDT),,option year three pricing- see exhibit s for m...,G 4 S,USA,46.0000,,option year three pricing exhibit information,option year three pricing exhibit information
2,SKOPJ,7510,GRANTS/CONT/SUBSIDY,VALUE ADDED TAXES (V,Wed May 06 2020 09:54:32 GMT-0400 (EDT),fm ethyl alcohol 05/04/20,ethyl alcohol 1000 ml 96%,DOOEL EURO FARM BITOLA,MKD,6.4911,ethyl alcohol,ethyl alcohol 1000,ethyl alcohol ethyl alcohol 1000
3,KAMPA,D322,TRANSPORT OF THINGS,TRANSPORT GOVT PROP,Tue May 19 2020 06:49:26 GMT-0400 (EDT),2nd option yr against contract sge50017d0027,jude lumala~,VIZOCOM,ARE,0.0000,option contract sge50017d0027,jude lumala,option contract sge50017d0027 jude lumala
4,DILI_,Z1ND,"RENTS, COMM&UTILITIES",SEWAGE,Fri May 22 2020 06:05:53 GMT-0400 (EDT),caltech/sewage collection for embassy (june 2020),septic tank pump-out at back building 2 tanks...,Caltech General Contracting,TMP,760.0000,caltech sewage collection embassy june 2020,septic tank pump back building tanks litres...,caltech sewage collection embassy june 2020 s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
567190,NEWDE,9540,SUPPLIES & MATERIALS,"SECURITY SUPPLIES, M",Mon Jun 29 2020 03:24:00 GMT-0400 (EDT),laser cut 12mm metal sheet for grille of enclave,12 mm laser cut sheet; powder coated in glossy...,Hindustan Steel Trading,IND,422.0717,laser 12mm metal sheet grille enclave,laser sheet powder coated glossy white emb...,laser 12mm metal sheet grille enclave laser...
567191,THEHA,6515,SUPPLIES & MATERIALS,MEDICAL SUPPLIES,Wed Apr 01 2020 09:52:52 GMT-0400 (EDT),hu: otc meds health unit,vicks dayquil cough cold flu relief 24 liqu...,AMAZON.COM LLC,USA,0.0000,meds health unit,vicks dayquil cough cold relief liquicaps,meds health unit vicks dayquil cough cold r...
567192,RIYAD,8135,TRANSPORT OF THINGS,HHE PACKAGE&CRATING,Mon Jun 01 2020 03:10:54 GMT-0400 (EDT),dlivery/task order for hhe-Locationhi for mr. ...,packing charges for hhe @ 2.10/ net kg. (300kg...,ATCO-EAST WEST EXPRESS,SAU,168.0000,dlivery task order locationhi name feeney,packing charges 300kgs east west express ...,dlivery task order locationhi name feeney pa...
567193,DSATA,R408,OTHER SERVICES,CONTRACTADVIS AND AS,Mon Jun 29 2020 07:48:05 GMT-0400 (EDT),lumbee NAME (niger),niger course support,LUMBEE TRIBE ENTERPRISES LLC,USA,0.0000,lumbee name niger,niger course support,lumbee name niger niger course support
567194,DUBAI,5130,SUPPLIES & MATERIALS,BLDG REPR SUPPL/MAIL,Tue Jun 30 2020 08:14:23 GMT-0400 (EDT),hh Location:cons obo612:daniela zadrozny:mr ma...,3 pin plugsvolex,MEGSONS ENTERPRISES,ARE,13.0683,location cons obo612 daniela zadrozny materi...,plugsvolex,location cons obo612 daniela zadrozny materi...

In [9]:
df.shape

(567195, 13)

In [10]:
import pandas_dedupe

In [11]:
#To perform active machine learning
df = pandas_dedupe.dedupe_dataframe(df,['clean_title_desc'])

Importing data ...
Reading from dedupe_dataframe_learned_settings
Clustering...
# duplicate sets 86221

In [12]:
df

,BUSINESS_UNIT,PSC_CODE,OBJ_CODE,SUB_OBJ_DESCR,ORDER_DATE,ORDER_TITLE,LINE_DESCRIPTION,VENDOR_NAME,VENDOR_COUNTRY,COST,clean_title,clean_desc,clean_title_desc,cluster id,confidence
0,addis,v212,transport of things,hhe packagecrating,thu apr 23 2020 00:56:56 gmt-0400 (edt),state/gso/shiping-aaron name hhe exp airfreigh...,air freight service for the export of mr. name...,ethiopian airlines,eth,7963.4868,state shiping aaron name airfreight service,freight service export name cardona shipment n...,state shiping aaron name airfreight service fr...,0,0.981527
1,newde,s206,grants/cont/subsidy,value-added taxes,thu apr 16 2020 10:17:00 gmt-0400 (edt),,option year three pricing- see exhibit s for m...,g 4 s,usa,46.0,,option year three pricing exhibit information,option year three pricing exhibit information,1,0.981527
2,skopj,7510,grants/cont/subsidy,value added taxes (v,wed may 06 2020 09:54:32 gmt-0400 (edt),fm ethyl alcohol 05/04/20,ethyl alcohol 1000 ml 96,dooel euro farm bitola,mkd,6.4911,ethyl alcohol,ethyl alcohol 1000,ethyl alcohol ethyl alcohol 1000,4,0.981527
3,kampa,d322,transport of things,transport govt prop,tue may 19 2020 06:49:26 gmt-0400 (edt),2nd option yr against contract sge50017d0027,jude lumala,vizocom,are,0.0,option contract sge50017d0027,jude lumala,option contract sge50017d0027 jude lumala,8,0.981527
4,dili_,z1nd,"rents, commutilities",sewage,fri may 22 2020 06:05:53 gmt-0400 (edt),caltech/sewage collection for embassy (june 2020),septic tank pump-out at back building 2 tanks ...,caltech general contracting,tmp,760.0,caltech sewage collection embassy june 2020,septic tank pump back building tanks litres pe...,caltech sewage collection embassy june 2020 se...,6589,0.981527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567190,newde,9540,supplies materials,"security supplies, m",mon jun 29 2020 03:24:00 gmt-0400 (edt),laser cut 12mm metal sheet for grille of enclave,12 mm laser cut sheet powder coated in glossy ...,hindustan steel trading,ind,422.0717,laser 12mm metal sheet grille enclave,laser sheet powder coated glossy white embassy...,laser 12mm metal sheet grille enclave laser sh...,16913,0.981527
567191,theha,6515,supplies materials,medical supplies,wed apr 01 2020 09:52:52 gmt-0400 (edt),hu: otc meds health unit,vicks dayquil cough cold flu relief 24 liquicaps,amazon.com llc,usa,0.0,meds health unit,vicks dayquil cough cold relief liquicaps,meds health unit vicks dayquil cough cold reli...,85661,0.981527
567192,riyad,8135,transport of things,hhe packagecrating,mon jun 01 2020 03:10:54 gmt-0400 (edt),dlivery/task order for hhe-locationhi for mr. ...,packing charges for hhe 2.10/ net kg. (300kgs)...,atco-east west express,sau,168.0,dlivery task order locationhi name feeney,packing charges 300kgs east west express quote...,dlivery task order locationhi name feeney pack...,85662,0.981527
567193,dsata,r408,other services,contractadvis and as,mon jun 29 2020 07:48:05 gmt-0400 (edt),lumbee name (niger),niger course support,lumbee tribe enterprises llc,usa,0.0,lumbee name niger,niger course support,lumbee name niger niger course support,7051,0.981527
567194,dubai,5130,supplies materials,bldg repr suppl/mail,tue jun 30 2020 08:14:23 gmt-0400 (edt),hh location:cons obo612:daniela zadrozny:mr ma...,3 pin plugsvolex,megsons enterprises,are,13.0683,location cons obo612 daniela zadrozny materials,plugsvolex,location cons obo612 daniela zadrozny material...,40316,0.981527

In [13]:
#Convert dataframe to csv format
df.to_csv(r'combinedq1-q3dedupe.csv', index = False)